name: 'Code Risk Analyzer'
description: 'Analyze Source code files to determine defect risk'
inputs:
  repository:  # repo
    description: 'repo to analyze'
    required: true
  user:  # repo
    description: 'user for repo'
    required: true
  github_token:  # repo
    description: 'github token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'