name: 'code-risk-analyzer'

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  code-risk-analyzer:
    # Name the Job
    name: Code Risk Analyzer
    # Set the type of machine to run on
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Code Risk Analyzer
        uses: ./
        with:
          repository: ${{ github.repository }}
          user: ${{ github.repository_owner }}
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}